
replicaCount: 1
image: confluentinc/cp-enterprise-control-center
imageTag: 7.4.3
imagePullPolicy: IfNotPresent
imagePullSecrets:
serviceHttpPort: 9021
configurationOverrides:
  "replication.factor": "3"
heapOptions: "-Xms512M -Xmx512M"
customEnv: {}
resources: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
# jmx:
#   port: 5555
# prometheus:
#   jmx:
#     enabled: false
#     image: solsson/kafka-prometheus-jmx-exporter@sha256
#     imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
#     port: 5556
#     resources: {}
kafka:
  bootstrapServers: ""
cp-schema-registry:
  url: ""

cp-kafka-connect:
  url: ""

cp-ksql-server:
  url: ""

cp-zookeeper:
  url: ""  
