
## ------------------------------------------------------
## Kafka
## ------------------------------------------------------

## Number of Kafka brokers
brokers: 3
image: confluentinc/cp-server
imageTag: 7.4.3
imagePullPolicy: IfNotPresent
imagePullSecrets:
podManagementPolicy: OrderedReady
updateStrategy: RollingUpdate
securityContext: {}
configurationOverrides:
  "offsets.topic.replication.factor": "3"
  "listener.security.protocol.map": |-
   PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
customEnv: {}
persistence:
  enabled: true
  size: 1Gi
  disksPerBroker: 1

## Kafka JVM Heap Option
heapOptions: "-Xms512M -Xmx512M"
resources: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
jmx:
  port: 5555
prometheus:
  jmx:
    enabled: false
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    imagePullPolicy: IfNotPresent
    port: 5556
    resources: {}

nodeport:
  enabled: false
  servicePort: 19092
  firstListenerPort: 31090

## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  enabled: true
  servers: 3
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
  url: ""
